name: build-latest-release

on:
  workflow_dispatch:

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 创建版本号
        id: set_version
        run: |
          echo "3.0.$(date -d '+8 hours' +'%Y%m%d%H%M')" > version_number
          echo "version=$(cat version_number)" >> $GITHUB_ENV

      - name: Upload Version Artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version_number
  build-frontend:
    runs-on: ubuntu-latest
    needs: [ generate-version ]
    steps:
      - name: Checkout code Now Code
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Checkout code front end
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPOSITORY_FRONT }}
          path: './msaber-front'
          ref: 'prod'
          token: ${{ secrets.PERSON_ACCESS_TOKEN }}

      - name: Download Version Artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Read Version
        id: read_version
        run: echo "version=$(cat version_number)" >> $GITHUB_ENV

      - name: Update front version in version.ts
        run: |
          echo "export const version = '${{ env.version }}';" > msaber-front/version.ts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: msaber-front/package-lock.json

      - name: Build Frontend
        run: |
          cd msaber-front
          npm ci
          npm run build

      - name: Upload Frontend Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-front-dist
          path: msaber-front/dist/MediaSaber/browser

  build-backend:
    runs-on: ubuntu-latest
    needs: [ generate-version ]
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:

      - name: Checkout code back end
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPOSITORY_BACK }}
          path: './msaber-back'
          ref: 'prod'
          token: ${{ secrets.PERSON_ACCESS_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./msaber-back/go.mod
          cache: true
          cache-dependency-path: ./msaber-back/go.sum

      - name: Download Version Artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Read Version
        id: read_version
        run: echo "version=$(cat version_number)" >> $GITHUB_ENV

      - name: Update backend softwareVersion file
        run: |
          mkdir -p msaber-back/internal/svc/cert
          echo "${{ env.version }}" > msaber-back/internal/svc/cert/softwareVersion

      - name: Build for ${{ matrix.arch }}
        run: |
          cd msaber-back
          CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.arch }} go build -a --trimpath -ldflags="-X 'github.com/xylplm/media-saber-back-end/internal/svc.sqlDebug=false'" -o dist/linux/${{ matrix.arch }}/mediaSaber .

      - name: Prepare Files
        run: |
          mkdir -p msaber-back-${{ matrix.arch }}
          mkdir -p msaber-back-${{ matrix.arch }}/static
          cp -r msaber-back/dist msaber-back-${{ matrix.arch }}/dist
          cp -r msaber-back/etc msaber-back-${{ matrix.arch }}/etc
          cp -r msaber-back/static msaber-back-${{ matrix.arch }}/static
          cp -r msaber-back/doc msaber-back-${{ matrix.arch }}/doc

      - name: Upload Backend Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact-backend-${{ matrix.arch }}
          path: msaber-back-${{ matrix.arch }}

  docker-setup:
    runs-on: ubuntu-latest
    needs: [ build-frontend, build-backend ]
    steps:
      - name: Checkout code Now Code
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Download Version Artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Read Version
        id: read_version
        run: echo "version=$(cat version_number)" >> $GITHUB_ENV

      - name: Download Frontend Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: my-artifact-front-*
          merge-multiple: true
          path: msaber-front


      - run: ls -R msaber-front

      - name: Download Backend Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: my-artifact-backend-*
          merge-multiple: true
          path: msaber-back

      - run: ls -R msaber-back

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/media-saber:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/media-saber:${{ env.version }}
          push: true
  gen-release:
    runs-on: ubuntu-latest
    needs: [docker-setup]
    steps:
      - name: Checkout code Now Code
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Download Version Artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Read Version
        id: read_version
        run: echo "version=$(cat version_number)" >> $GITHUB_ENV

      - name: Download Frontend Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: my-artifact-front-*
          merge-multiple: true
          path: msaber-front

      - run: ls -R msaber-front

      - name: Download Backend Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: my-artifact-backend-*
          merge-multiple: true
          path: msaber-back

      - run: ls -R msaber-back

      - name: Prepare Files for Release amd64
        run: |
          mkdir -p release/msaber-front
          mkdir -p release/msaber-back
          mkdir -p release/msaber-back/static
          mkdir -p release/msaber-back/doc
          cp -r msaber-front/* release/msaber-front/
          cp -r msaber-back/dist/linux/amd64/mediaSaber release/msaber-back/mediaSaber
          cp -r msaber-back/etc release/msaber-back/
          cp -r msaber-back/static release/msaber-back/static
          cp -r msaber-back/doc release/msaber-back/doc

      - name: Create ZIP Archive amd64
        run: |
          cd release
          tar -czvf mediaSaber-amd64.tar.gz msaber-front msaber-back


      - name: Prepare Files for Release arm64
        run: |
          cp -r msaber-back/dist/linux/arm64/mediaSaber release/msaber-back/mediaSaber

      - name: Create ZIP Archive arm64
        run: |
          cd release
          tar -czvf mediaSaber-arm64.tar.gz msaber-front msaber-back

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset - amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/mediaSaber-amd64.tar.gz
          asset_name: mediaSaber-amd64.tar.gz
          asset_content_type: application/gzip

      - name: Upload Release Asset - arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/mediaSaber-arm64.tar.gz
          asset_name: mediaSaber-arm64.tar.gz
          asset_content_type: application/gzip

      - name: Update version File
        run: echo "${{ env.version }}" > version

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add version
          git commit -m "Update version with ${{ env.version }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSON_ACCESS_TOKEN }}
          branch: main

  update-version:
    runs-on: ubuntu-latest
    needs: [ gen-release ]
    steps:
      - name: Checkout code Now Code
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Download Version Artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Read Version
        id: read_version
        run: echo "version=$(cat version_number)" >> $GITHUB_ENV

      - name: Checkout code front end
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPOSITORY_FRONT }}
          path: './msaber-front'
          ref: 'main'
          token: ${{ secrets.PERSON_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Upgrade Frontend version json
        run: |
          bash version_update.sh -r ./msaber-front -f ./upgrade/latest/latest-front.json -v ${{ env.version }}

      - name: Checkout code back end
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPOSITORY_BACK }}
          path: './msaber-back'
          ref: 'main'
          token: ${{ secrets.PERSON_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Upgrade Backend version json
        run: |
          bash version_update.sh -r ./msaber-back -f ./upgrade/latest/latest-back.json -v ${{ env.version }}

      - name: Commit and Push Changes
        run: |
          bash version_commit.sh
